name: Update Subscription and README

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 设置作业超时时间
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run w-sub to update subscriptions
        run: python w-sub.py
      
      - name: Upload debug logs
        uses: actions/upload-artifact@v4  # 更新到v4版本
        with:
          name: debug-logs
          path: |
            w-sub.log
            node_test_debug.txt
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add subscription_all.txt subscription_best.txt README.md
          # 检查是否有更改
          if git diff --staged --quiet; then
            echo "没有检测到更改，跳过提交"
          else
            git commit -m 'Update subscription files and README'
            git push
          fi